title: Google Foobar
iconURL: assets/google.png

markdown: kramdown

# for a clean URL
permalink: :slug

social:
  twitter: evilj0ker19
  github: rajat19/foobar

plugins:
 - jekyll-feed
 - jekyll-seo-tag

default_languages: java py